services:
  - type: web
    name: realestate-api
    env: python
    plan: free
    buildCommand: poetry install
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"